### ISSUE TITLE
The implementation of bstree_replace() may incorrect

### ISSUE THREAD

**Issue by zjx20** [fbuihuu/libtree#8]
It should maintain "thread" pointers by updating them to point to the new node as well. 
For instance:

``` c
set_next(new, get_prev(old)); // NOTE: it just telling the point, not necessary to be correct
```

In my test program, an infinite lookup loop comes up easily with random datasets and with using `bstree_replace()`. But everything was fine without `bstree_replace()`.

**Comment by fbuihuu** [comment]
Could you send me your test program ?
Thanks.

**Comment by zjx20** [comment]
Sure, please take a look this url:
https://gist.github.com/zjx20/a5edb2a4869639f58c81#file-bug_report-cpp-L55

You can test the code with or without `#define USE_BSTREE_REPLACE`.

**Comment by fbuihuu** [comment]
That should be fixed on master. Could you give it a test ?

**Comment by zjx20** [comment]
It is still getting wrong.

For example:

```
          A
         / \
        B   C
         \
          D
```

If the node D is going to be replaced now, the left pointer of the node A will be modified to point to the new node D' which it shouldn't to be:

``` c
    /* update the thread links */
    prev = bstree_prev(old);     // prev is B
    if (prev && prev != parent)  // get false
        set_next(new, prev);     // skipped
    next = bstree_next(old);     // next is A
    if (next && next != parent)  // get true
        set_prev(new, next);     // wrong!
```

**Comment by fbuihuu** [comment]
Assuming lexical order A < B < C < D, how did you generate such a tree ?
Can you provide some (simple) test case instead ?
Thanks.

**Comment by zjx20** [comment]
The ABCD just symbols of nodes, not keys.

A=4, B=1, C=5, D=3  // updated again

It should be easy to construct such a tree, seems bst does not rotate at all.

**Comment by fbuihuu** [comment]
Again provide a test case and see how the tree is built.

**Comment by zjx20** [comment]
Please test this code, it shows the bug: https://gist.github.com/zjx20/453e58d9b1c600cdca76#file-bug_report2-cpp-L55
You can also comment the line `#define USE_BSTREE_REPLACE` and then run it again.

I'm sorry for the mistake I made in my sample, twice. But as I said, it is easy to construct such a tree.
Why do I have to provide a test case for this? You should take good care of your code, please.

**Comment by fbuihuu** [comment]
> Why do I have to provide a test case for this?

Because you're a nice guy who wants to make life easier to another nice guy ? ;)

> You should take good care of your code, please.

I do and that's the reason why I'm answering you...

Please give the branch 'fix-bst-replace' a try.

**Comment by zjx20** [comment]
It is correct, at least in my test.
